Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  CountComments: false
  Max: 250

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 7

Style/SpecialGlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Naming/PredicateName:
  NamePrefix:
    - is_
    - has_

  NamePrefixBlacklist:
    - is_
    - has_

Metrics/AbcSize:
  Max: 45

Metrics/PerceivedComplexity:
  Max: 10

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - Gemfile

Layout/ExtraSpacing:
  AllowForAlignment: true
