require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Naming/RescuedExceptionsVariableName:
  PreferredName: 'exception'

Style/FormatStringToken:
  EnforcedStyle: template

RSpec:
  Exclude:
    - 'spec/factories/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

# while that is a good rule, AR objects can't be properly instance_double'd
RSpec/VerifiedDoubles:
  Enabled: false

# ----------------- ATTENTION -------------------------------------------------
# Temporary, til time to fix new violations introduced by new rubocop version
# -----------------------------------------------------------------------------
Lint/UnmodifiedReduceAccumulator:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/RepeatedExample:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/RepeatedDescription:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'docker/**/*'
    - 'doc/**/*'
    - 'bin/**/*'
    - 'Rakefile'
    - 'config.ru'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
