adapters:
  rspec:
    adapter: rspec
    file_pattern: ".*_spec.rb$"
  #
  # phpunit:
  #   adapter: Koine\TestRunner\Adapter\Php\PHPUnit
  #   file_pattern: "*Test.php"
  #
  # codeception:
  #   adapter: Koine\TestRunner\Adapter\Php\Codeception
  #   file_pattern: "*Spec.php"
  #
  # jest:
  #   adapter: Koine\TestRunner\Adapter\Javascript\Jest
  #   file_pattern: "*_(test|spec).(js|jsx)"
