#!/usr/bin/env ruby
lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'fileutils'
require 'koine/test_runner'
require 'yaml'

configuration = Koine::TestRunner::Configuration.new(ARGV)
runner = Koine::TestRunner::Builder.new(configuration).build
runner.run(configuration)
