#!/usr/bin/env ruby

require 'bundler/setup'
require 'koine/test_runner'
require 'yaml'

arguments = Koine::TestRunner::Arguments.new(ARGV)
runner = Koine::TestRunner::Builder.new(arguments).build
runner.run(arguments.run_options)
